AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-trader

  App that enables interaction with capital.com API for viewing market information, 
  execute trade transactions and develop automated trading strategies.

  IMPORTANT: This template/app assumes you have created the following Parameter Store parameters on aws with correct values:
  - /cloud-trader/capitalDemoUrl  -> Type STRING
  - /cloud-trader/identifier      -> Type STRING
  - /cloud-trader/key             -> Type SECURESTRING
  - /cloud-trader/password        -> Type SECURESTRING
  
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 15
    MemorySize: 128
    Architectures:
      - x86_64
    Layers:
      - TODO
    Environment:
      Variables:
        TODO: TODO

Resources:
  ############################################################################  ->  State Machines


  ############################################################################  ->  Lambda Functions
  GetCapitalSession:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/capital/start-session/
      Handler: startSession.handler
      # Events:
      #   HelloWorld:
      #     Type: HttpApi 
      #     Properties:
      #       Path: /hello
      #       Method: get











Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
