AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-trader

  App that enables interaction with capital.com API for viewing market information, 
  execute trade transactions and develop automated trading strategies.

  IMPORTANT: This template/app assumes you have created the following Parameter Store parameters on aws with correct values:
  - /cloud-trader/capitalDemoUrl  -> Type STRING
  - /cloud-trader/identifier      -> Type STRING
  - /cloud-trader/key             -> Type SECURESTRING
  - /cloud-trader/password        -> Type SECURESTRING
  
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 15             # TODO: Check if reduced time between 3 to 5 seconds would be sufficient.
    MemorySize: 128
    Architectures:
      - x86_64
    Layers:
      - !Ref AWSServicesLayer
      - !Ref CommonLayer
    Environment:
      Variables:
        CT_IDENTIFIER: /cloud-trader/identifier         # TODO: Each user would persist as account settings in DB
        CT_KEY: /cloud-trader/key                       # TODO: Each user would persist as account settings in DB
        CT_PASSWORD: /cloud-trader/password             # TODO: Each user would persist as account settings in DB
        CT_DEMO_URL: /cloud-trader/capitalDemoUrl       # TODO: Each user would persist as account settings in DB
        SESSION_ENDPOINT: /session

Resources:
  ############################################################################  ->  State Machines


  ############################################################################  ->  Lambda Functions
  StartCapitalSession:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StartCapitalSessionFn
      CodeUri: functions/capital/start-session/
      Handler: startSession.handler
      Policies: 
        - !Ref ReadParameterStoreValues
      # Events:
      #   HelloWorld:
      #     Type: HttpApi 
      #     Properties:
      #       Path: /hello
      #       Method: get


############################################################################  ->  Role/Policy for Lambda fn to use
  ReadParameterStoreValues:       #--> Using explicit Policy definition. There is no standard Connector
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ReadParameterStoreValues      
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParametersByPath
              # - ssm:PutParameter
            Resource: '*'


  ############################################################################  ->  Layers
  AWSServicesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWSServicesLayer
      Description: All AWS services used by Cloud-Trader app.
      ContentUri: './layers/aws-services'
      CompatibleRuntimes:
        - nodejs18.x

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CommonLayer
      Description: Shared OR Common variables and helper functions.
      ContentUri: './layers/common'
      CompatibleRuntimes:
        - nodejs18.x


  ############################################################################  ->  Dynamo DBs
  SessionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Session
      PrimaryKey:           # { sessionID: '4t£f38curqjf' }
        Name: sessionID
        Type: String
