AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-trader

  App that enables interaction with capital.com API for viewing market information, 
  execute trade transactions and develop automated trading strategies.

  IMPORTANT: This template/app assumes you have created the following Parameter Store parameters on aws with correct values:
  - /cloud-trader/capitalDemoUrl  -> Type STRING
  - /cloud-trader/identifier      -> Type STRING
  - /cloud-trader/key             -> Type SECURESTRING
  - /cloud-trader/password        -> Type SECURESTRING
  
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 15             # TODO: Check if reduced time between 3 to 5 seconds would be sufficient.
    MemorySize: 128
    Architectures:
      - x86_64
    # Layers:
    #   - TODO
    # Environment:
    #   Variables:
    #     TODO: TODO

Resources:
  ############################################################################  ->  State Machines


  ############################################################################  ->  Lambda Functions
  StartCapitalSession:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StartCapitalSessionFn
      CodeUri: functions/capital/start-session/
      Handler: startSession.handler
      Policies: 
        - !Ref ReadParameterStoreValues
      # Events:
      #   HelloWorld:
      #     Type: HttpApi 
      #     Properties:
      #       Path: /hello
      #       Method: get


######################################################## --> ROLE/POLICY FOR LAMBDA FN TO USE PARAMETER STORE
  ReadParameterStoreValues:       #--> Using explicit Policy definition. There is no standard Connector
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ReadParameterStoreValues      
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParametersByPath
              # - ssm:PutParameter
            Resource: '*'
