AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-trader

  App that enables interaction with capital.com API for viewing market information, 
  execute trade transactions and develop automated trading strategies.

  IMPORTANT: This template/app assumes you have created the following Parameter Store parameters on aws with correct values:
  - /cloud-trader/capitalDemoUrl  -> Type STRING
  - /cloud-trader/identifier      -> Type STRING
  - /cloud-trader/key             -> Type SECURESTRING
  - /cloud-trader/password        -> Type SECURESTRING
  
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 15             # TODO: Check if reduced time between 3 to 5 seconds would be sufficient.
    MemorySize: 128
    Architectures:
      - x86_64
    Layers:
      - !Ref ServicesUtilsLayer
    Environment:
      Variables:
        CT_IDENTIFIER: /cloud-trader/identifier         # TODO: Each user would persist as account settings in DB
        CT_KEY: /cloud-trader/key                       # TODO: Each user would persist as account settings in DB
        CT_PASSWORD: /cloud-trader/password             # TODO: Each user would persist as account settings in DB
        CT_DEMO_URL: /cloud-trader/capitalDemoUrl       # TODO: Each user would persist as account settings in DB
        SESSION_ENDPOINT: /session
        MARKET_CATEGORIES_ENDPOINT: /marketnavigation
        SESSION_TABLE_NAME: Session
        MARKET_CATEGORIES_TABLE_NAME: MarketCategories
        SESSION_TABLE_KEY_VALUE: only1session

Resources:
  ############################################################################  ->  State Machines
  GetSessionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state-machines/get-session.asl.yaml
      Type: STANDARD
      DefinitionSubstitutions:
        StartCapitalSessionArn: !GetAtt StartCapitalSession.Arn
        GetDbSessionArn: !GetAtt GetDbSession.Arn
        ValidateSessionArn: !GetAtt ValidateSession.Arn
        SaveSessionArn: !GetAtt SaveSession.Arn
      Events:
        GatewayTrigger:
          Type: Api
          Properties:
            Path: /get-session
            Method: GET
            RestApiId: !Ref CloudTraderGateway
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref StartCapitalSession
        - LambdaInvokePolicy:
            FunctionName: !Ref GetDbSession
        - LambdaInvokePolicy:
            FunctionName: !Ref ValidateSession
        - LambdaInvokePolicy:
            FunctionName: !Ref SaveSession


  ############################################################################  ->  API Gateways
  CloudTraderGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: CloudTraderGateway
      StageName: dev


  ############################################################################  ->  Lambda Functions
  StartCapitalSession:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StartCapitalSession
      CodeUri: functions/capital/start-session/
      Handler: startSession.handler
      Policies: 
        - !Ref ReadParameterStoreValues

  GetDbSession:
    Type: AWS::Serverless::Function
    Connectors:
      ToSessionTable:
        Properties:
          Destination: 
            Id: SessionTable
          Permissions:
            - Read
    Properties:
      FunctionName: GetDbSession
      CodeUri: functions/db/get-session/
      Handler: getDbSession.handler

  ValidateSession:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ValidateSession
      CodeUri: functions/capital/validate-session/
      Handler: validateSession.handler
      
  SaveSession:
    Type: AWS::Serverless::Function
    Connectors:
      ToSessionTable:
        Properties:
          Destination: 
            Id: SessionTable
          Permissions:
            - Write
    Properties:
      FunctionName: SaveSession
      CodeUri: functions/db/save-session/
      Handler: saveSession.handler

  GetMarketCategories:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetMarketCategories
      CodeUri: functions/capital/markets/
      Handler: getMarketCategories.handler
      Policies: 
        - !Ref ReadParameterStoreValues


############################################################################  ->  Role/Policy for Lambda fn to use
  ReadParameterStoreValues:       #--> Using explicit Policy definition. There is no standard Connector
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ReadParameterStoreValues      
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParametersByPath
              # - ssm:PutParameter
            Resource: '*'


  ############################################################################  ->  Layers
  ServicesUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ServicesUtilsLayer
      Description: All AWS services used by Cloud-Trader app.
      ContentUri: './layers/services-utils'
      CompatibleRuntimes:
        - nodejs18.x

  ############################################################################  ->  Dynamo DBs
  SessionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Session    # MUST be thesame as SESSEION_TABLE_NAME enviromnent variable above!!!
      PrimaryKey:           # { sessionID: 'only1session' }
        Name: sessionID
        Type: String
  
  MarketCategoriesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MarketCategories    # MUST be thesame as MARKET_CATEGORIES_TABLE_NAME enviromnent variable above!!!
      PrimaryKey:           # { sessionID: 'only1session' }
        Name: id
        Type: String
